=== bermud/oostethys/java/oostethys-java-server/src/main/resources/xml/oostethys/0.1.0/xsd/oostethys.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" targetNamespace="http://www.oostethys.org/schemas/0.1.0/oostethys"
	xmlns:oost="http://www.oostethys.org/schemas/0.1.0/oostethys"
	xmlns:oostcsv="http://www.oostethys.org/schemas/0.1.0/oostethys-csv"
	xmlns:oostnc="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">

	<xs:import namespace="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf"
		schemaLocation="oostethys-netcdf.xsd">
	</xs:import>
	<xs:import namespace="http://www.oostethys.org/schemas/0.1.0/oostethys-csv"
		schemaLocation="oostethys-csv.xsd">
	</xs:import>

	<xs:element name="oostethys">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="webServerURL" type="xs:string"
					minOccurs="0" />
				<xs:element ref="oost:serviceContact" />
				<xs:element ref="oost:components" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="systemContact">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="oost:contact">
					<xs:attribute name="ref" type="xs:IDREF" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="serviceContact">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="oost:contact">
				</xs:extension>
			</xs:complexContent>

		</xs:complexType>
	</xs:element>

	<xs:element name="referencedContact">
		<xs:complexType>
			<xs:attribute name="ref" type="xs:IDREF" />
		</xs:complexType>
	</xs:element>


	<xs:complexType name="contact">

		<xs:sequence>
			<xs:element name="urlOrganization" type="xs:anyURI" />
			<xs:element name="longNameOrganization" type="xs:string" />
			<xs:element name="shortNameOrganization" type="xs:string" />
			<xs:element name="individualName" type="xs:string" />
			<xs:element name="individualEmail" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="type" use="required" type="xs:anyURI" />
		<xs:attribute name="id" type="xs:ID" use="required" />

	</xs:complexType>



	<xs:element name="components">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:system" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="system">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:metadata" />
				<xs:element ref="oost:extend" minOccurs="0" />

				<!-- either has componenets or output -->
				<xs:choice>
					<xs:element ref="oost:components" />
					<xs:element ref="oost:output" />
				</xs:choice>
			</xs:sequence>

		</xs:complexType>
	</xs:element>

	<xs:element name="extend">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:timePeriod" minOccurs="0" />
				<xs:element ref="oost:boundingBox" minOccurs="0" />

			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="metadata">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="systemLongName" type="xs:string" />
				<xs:element name="systemShortName" type="xs:string" />
				<xs:element name="systemIdentifier" type="xs:anyURI" />
				<xs:element name="systemType" type="xs:anyURI" />
				<xs:element ref="oost:systemMetadataProperty" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element ref="oost:systemContacts" />
				<xs:element ref="oost:lastKnownLocation" minOccurs="0"
					maxOccurs="1">

				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="systemContacts">
		<xs:complexType>
			<xs:sequence minOccurs="1">
				<xs:element ref="oost:systemContact" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element ref="oost:referencedContact" minOccurs="0"
					maxOccurs="unbounded"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="lastKnownLocation">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="srsName" use="required"></xs:attribute>
				</xs:extension>
			</xs:simpleContent>


		</xs:complexType>


	</xs:element>

	<xs:element name="systemMetadataProperty">
		<xs:complexType>
			<xs:attribute name="propertyURI" type="xs:string" />
		</xs:complexType>
	</xs:element>


	<xs:element name="timePeriod">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="start" type="xs:string" />
				<xs:element name="end" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="endOfDeployment" type="xs:NMTOKEN" />
	<xs:element name="boundingBox">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:envelope" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="envelope">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:lowerCorner" />
				<xs:element ref="oost:upperCorner" />
			</xs:sequence>
			<xs:attribute name="srsName" use="required" type="xs:NMTOKEN" />
		</xs:complexType>
	</xs:element>
	<xs:element name="lowerCorner" type="xs:string" />
	<xs:element name="upperCorner" type="xs:string" />
	<xs:element name="url" type="xs:anyURI" />
	<xs:element name="nameOrganization" type="xs:string" />
	<xs:element name="shortNameOrganization" type="xs:NCName" />
	<xs:element name="individualName" type="xs:string" />
	<xs:element name="individualEmail" type="xs:string" />

	<xs:element name="output">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:sourceConfiguration" minOccurs="0" />
				<xs:element ref="oost:variables" minOccurs="0" />
				<xs:element ref="oost:values" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="sourceConfiguration">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="oostnc:oostethys-netcdf" />
				<xs:element ref="oostcsv:oostethys-csv" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="variables">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="oost:variable" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="variable">
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:string" />
			<xs:attribute name="uri" use="optional" type="xs:anyURI" />
			<xs:attribute name="uom" use="optional" type="xs:string" />
			<xs:attribute name="isCoordinate" use="optional" type="xs:boolean" />
			<xs:attribute name="isTime" use="optional" type="xs:boolean" />
			<xs:attribute name="referenceFrame" use="optional" type="xs:anyURI" />
		</xs:complexType>

	</xs:element>
	<xs:element name="values" type="xs:string" />


</xs:schema>

=== bermud/oostethys/branches/without_maven/component/server/java/src/test/oostethys-roym.xml
<?xml version="1.0" encoding="UTF-8"?>
<oostethys xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.oostethys.org/schemas/0.1.0/oostethys
	http://www.oostethys.org/schemas/0.1.0/oostethys.xsd">
	
	<webServerURL>http://localhost:8080</webServerURL>
	<serviceContact
		type="http://mmisw.org/mmi/20080520/obs.owl#serviceProvider"
		id="a1">
		<urlOrganization>http://www.pfel.noaa.gov</urlOrganization>
		<longNameOrganization>
			NOAA/NMFS/SWFSC Environmental Research Division
		</longNameOrganization>
		<shortNameOrganization>ERD</shortNameOrganization>
		<individualName />
		<individualEmail />
	</serviceContact>
	
	<components>
		<system>
			<metadata>
				<sytemLongName>Coastwatch Monthly SST Blended, Global, Experimental</sytemLongName>
				<systemShortName>aggregsatBA_sstamday</systemShortName>
				<systemIdentifier>urn:usgs:gov:model:um1-gom</systemIdentifier>
				<systemType>
					http://mmisw.org/mmi/platform#Satellite
				</systemType>
				<systemContacts>
					<systemContact
						type="http://mmisw.org/mmi/20080520/obs.owl#dataProvider"
						id="c1">
						<urlOrganization>
							org
						</urlOrganization>
						<longNameOrganization>
							a long name
						</longNameOrganization>
						<shortNameOrganization>
							shortName
						</shortNameOrganization>
						<individualName>FirstName lastName</individualName>
						<individualEmail>xxx@xxx.org</individualEmail>
					</systemContact>
				</systemContacts>
			</metadata>
			
			
			<output>
				
				<sourceConfiguration>
					<oostethys-netcdf
						xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
						<fileURL>
							http://oceanwatch.pfeg.noaa.gov/thredds/dodsC/satellite/BA/ssta/mday
						</fileURL>
						
						<variables>
							<variable shortName="altitude" />
							<variable shortName="lat" />
							<variable shortName="lon" />
							<variable shortName="time" />
							<variable shortName="BAssta" />
							
						</variables>
					</oostethys-netcdf>
					
					
				</sourceConfiguration>
				
			</output>
		</system>
		<system>
			<metadata>
				<sytemLongName> Coastwatch 8day Primary Productivity Experimental</sytemLongName>
				<systemShortName>aggregsatPN_bfp28day</systemShortName>
				<systemIdentifier>urn:usgs:gov:model:fvcom-gom</systemIdentifier>
				<systemType>http://mmisw.org/mmi/platform#Satellite </systemType>
				<systemContacts>
					<referencedContact ref="a1"/>
					
				</systemContacts>
			</metadata>
			
			
			
			<output>
				
				<sourceConfiguration>
					
					<oostethys-netcdf
						xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
						<fileURL> http://oceanwatch.pfeg.noaa.gov/thredds/dodsC/satellite/PN/bfp2/8day </fileURL>
						
						<variables>
							<variable shortName="altitude" />
							<variable shortName="lat" />
							<variable shortName="lon" />
							<variable shortName="time" />
							<variable shortName="PNbfp2" />
							
						</variables>
					</oostethys-netcdf>
					
				</sourceConfiguration>
				
			</output>
		</system>
		
	</components>
	
</oostethys>

=== bermud/oostethys/oostethys-java-server/src/test/resources/oostethys-csv.xml
<?xml version="1.0" encoding="UTF-8"?>
<oostethys xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:csv="http://www.oostethys.org/schemas/0.1.0/oostethys-csv"
	xsi:schemaLocation="http://www.oostethys.org/schemas/0.1.0/oostethys ../../main/resources/xml/oostethys/0.1.0/xsd/oostethys.xsd">


	<webServerURL></webServerURL>

	<!--  SOS service metadata -->
	<serviceContact type="http://mmisw.org/mmi/20080520/obs.owl#serviceProvider"
		id="a1">
		<urlOrganization>http://www.marinemetadata.org</urlOrganization>
		<longNameOrganization>Marine Metadata Interoperability Initiative
			(MMI)</longNameOrganization>
		<shortNameOrganization>MMI</shortNameOrganization>
		<individualName></individualName>
		<individualEmail></individualEmail>
	</serviceContact>

	<!--
		Components could be observing systems, platforms, sensors , etc...
	-->
	<components>
		<system>
			<metadata>
				<sytemLongName>Monterey Bay Aquarium Research Institute Observing
					System</sytemLongName>
				<systemShortName>MBARI</systemShortName>
				<systemIdentifier>urn:mbari:org</systemIdentifier>
				<systemType>http://mmisw.org/mmi/20080520/obs.owl#observationSystem</systemType>
				<systemContacts>
					<systemContact type="http://mmisw.org/mmi/20080520/obs.owl#dataProvider"
						id="c1">
						<urlOrganization>http://www.mbari.org</urlOrganization>
						<longNameOrganization>Monterey Bay Aquarium Research Institute
						</longNameOrganization>
						<shortNameOrganization>MBARI</shortNameOrganization>
						<individualName>John G</individualName>
						<individualEmail>xxx@yyy.org</individualEmail>
					</systemContact>
				</systemContacts>
			</metadata>

			<!--  A System could contain components or output.  -->

			<components>
				<system>
					<metadata>
						<sytemLongName>Mooring M2</sytemLongName>
						<systemShortName>m2</systemShortName>
						<systemIdentifier>uri:mbari:org:mooring:m2</systemIdentifier>
						<systemType>http://mmisw.org/mmi/20080516/platform#MooredBuoy</systemType>
						<systemContacts />
					</metadata>
					<components>
						<system>

							<!--  This system has outputs and no components -->

							<metadata>
								<sytemLongName>Serial CTD</sytemLongName>
								<systemShortName>1455</systemShortName>
								<systemIdentifier>urn:mbari:org:device:1455</systemIdentifier>
								<systemType>http://mmisw.org/mmi/20080529/sensor.owl#CTD</systemType>
								<systemContacts />
							</metadata>


							<output>
								<sourceConfiguration>
									<csv:oostethys-csv>
										<csv:inline type="csv" />
									</csv:oostethys-csv>
								</sourceConfiguration>


								<variables>
									<variable name="time" isCoordinate="true" uri="urn:ogc:phenomenon:time:iso8601"/>
									<variable uri="urn:ogc:phenomenon:latitude:wgs84"
										name="latitude" uom="degrees_north" isCoordinate="true" />
									<variable uri="urn:ogc:phenomenon:longitude:wgs84"
										name="longitude" uom="degrees_east" isCoordinate="true"  />
										<variable uri="http://marinemetadata.org/cf#Oxygen"
										name="Oxygen" uom="mmol/l" isCoordinate="false" />
									<variable
										uri="http://marinemetadata.org/cf#OxygenAirSaturation" name="OxygenAirSaturation"
										uom="percent" isCoordinate="false" />
									<variable uri="http://marinemetadata.org/cf#temperature"
										name="temperature" uom="deg C" isCoordinate="false" />
								</variables>
								
								
								<values>
								2008-06-16T19:56:41Z,36.69623,-122.39965,390,340.02,100.5,11.73
									2008-06-16T20:05:29Z,36.69623,-122.39965,390,339.51,100.36,11.73
									2008-06-16T20:16:43Z,36.69623,-122.39965,390,339.83,100.42,11.72
									2008-06-16T20:25:29Z,36.69623,-122.39965,390,339.44,100.33,11.73
									2008-06-16T20:36:41Z,36.69623,-122.39965,390,339.7,100.43,11.74
									2008-06-16T20:45:29Z,36.69623,-122.39965,390,339.5,100.35,11.73
									2008-06-16T20:56:41Z,36.69623,-122.39965,390,339.82,100.44,11.73
									2008-06-16T21:05:30Z,36.69623,-122.39965,390,339.54,100.35,11.73
									2008-06-16T21:16:41Z,36.69623,-122.39965,390,339.98,100.52,11.74
									2008-06-16T21:25:29Z,36.69623,-122.39965,390,339.8,100.42,11.72
									2008-06-16T21:36:42Z,36.69623,-122.39965,390,340.96,100.78,11.73
									2008-06-16T21:45:29Z,36.69623,-122.39965,390,339.46,100.36,11.74
									2008-06-16T21:56:41Z,36.69623,-122.39965,390,339.62,100.42,11.75
								
								</values>
							</output>
						</system>

					</components>
				</system>

			</components>
		</system>
	</components>
</oostethys>

=== bermud/oostethys/component/server/java/src/test/SimpleOostethys.xml
<?xml version="1.0" encoding="UTF-8"?>
<oostethys xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.oostethys.org/schemas/0.1.0/oostethys ../oostethys.xsd">

    <webServerURL>http://localhost:8080</webServerURL>
    <serviceContact type="http://mmisw.org/mmi/20080520/obs.owl#serviceProvider" id="a1">
        <urlOrganization>http://www.marinemetadata.org</urlOrganization>
        <longNameOrganization>Marine Metadata Interoperability Initiative (MMI)</longNameOrganization>
        <shortNameOrganization>MMI</shortNameOrganization>
        <individualName/>
        <individualEmail/>
    </serviceContact>

    <components>
        <system>
            <metadata>
                <sytemLongName>USGS Model</sytemLongName>
                <systemShortName>um</systemShortName>
                <systemIdentifier>urn:usgs:org:model1</systemIdentifier>
                <systemType>http://mmisw.org/mmi/20080520/obs.owl#numericalModel</systemType>
                <systemContacts>
                    <systemContact type="http://mmisw.org/mmi/20080520/obs.owl#dataProvider" id="c1">
                        <urlOrganization>http://www.usgs.org</urlOrganization>
                        <longNameOrganization>USGS</longNameOrganization>
                        <shortNameOrganization>USGS</shortNameOrganization>
                        <individualName>Rick Ludich</individualName>
                        <individualEmail>r@usgs.org</individualEmail>
                    </systemContact>
                </systemContacts>
            </metadata>

            <extend>
                <timePeriod>
                    <start>2008-06-05T04:30:00Z</start>
                    <end>2008-06-05T23:30:00Z</end>
                </timePeriod>
                <boundingBox>
                    <envelope srsName="urn:ogc:def:crs:EPSG:6.5:4326">
                        <lowerCorner>42.20551 -70.72384</lowerCorner>
                        <upperCorner>42.20551 -70.72384</upperCorner>
                    </envelope>
                </boundingBox>
            </extend>
<!--
            <output>

                <sourceConfiguration>
                    <oostethys-netcdf
                        xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
                        <fileURL>file:/Users/bermudez/Documents/workspace31/org.oostethys/etc/umassb_scituate.nc</fileURL>

                        <variables>
                            <variable standardName="Time"/>
                            <variable standardName="longitude"/>
                            <variable standardName="latitude"/>
                            <variable standardName="sea_surface_height"/>

                        </variables>
                    </oostethys-netcdf>

                </sourceConfiguration>
                <variables>
                    <variable name="Time" uri="urn:ogc:phenomenon:time:iso8601"
                        uom="hours since 2006-01-01 00:00 UTC" isTime="true"
                        isCoordinate="true"/>
                    <variable name="longitude" uri="urn:ogc:phenomenon:longitude:wgs84"
                        uom="degrees_east"/>
                    <variable name="latitude" uri="urn:ogc:phenomenon:latitude:wgs84"
                        uom="degrees_north"/>
                    <variable name="sea_surface_height"
                        uri="http://marinemetadata.org/cf#sea_surface_height" uom="meters"/>
                </variables>
                <values> 2008-06-05T04:30:00Z,42.20551,-70.72384,-1.01651
                    2008-06-05T05:30:00Z,42.20551,-70.72384,-1.761284
                    2008-06-05T06:30:00Z,42.20551,-70.72384,-2.052919
                    2008-06-05T07:30:00Z,42.20551,-70.72384,-1.811579
                    2008-06-05T08:30:00Z,42.20551,-70.72384,-1.114414
                    2008-06-05T09:30:00Z,42.20551,-70.72384,-0.151616
                    2008-06-05T10:30:00Z,42.20551,-70.72384,0.851955
                    2008-06-05T11:30:00Z,42.20551,-70.72384,1.641896
                    2008-06-05T12:30:00Z,42.20551,-70.72384,1.994201
                    2008-06-05T13:30:00Z,42.20551,-70.72384,1.843928
                    2008-06-05T14:30:00Z,42.20551,-70.72384,1.253456
                    2008-06-05T15:30:00Z,42.20551,-70.72384,0.370983
                    2008-06-05T16:30:00Z,42.20551,-70.72384,-0.621113
                    2008-06-05T17:30:00Z,42.20551,-70.72384,-1.475753
                    2008-06-05T18:30:00Z,42.20551,-70.72384,-1.951109
                    2008-06-05T19:30:00Z,42.20551,-70.72384,-1.923398
                    2008-06-05T20:30:00Z,42.20551,-70.72384,-1.406537
                    2008-06-05T21:30:00Z,42.20551,-70.72384,-0.548234
                    2008-06-05T22:30:00Z,42.20551,-70.72384,0.435682
                    2008-06-05T23:30:00Z,42.20551,-70.72384,1.319742</values>
            </output>
-->
          
            <components>
                <system>
                    <metadata>
                        <sytemLongName>test level 2</sytemLongName>
                        <systemShortName>sb1</systemShortName>
                        <systemIdentifier>uri:2</systemIdentifier>
                        <systemType>uri:type:x</systemType>
                        <systemContacts></systemContacts>
                    </metadata>
                    <output>
                    <sourceConfiguration>
                        <oostethys-netcdf
                            xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
                            <fileURL>file:/Users/bermudez/Documents/workspace31/org.oostethys/etc/umassb_scituate.nc</fileURL>
                            
                            <variables>
                                <variable standardName="Time"/>
                                <variable standardName="longitude"/>
                                <variable standardName="latitude"/>
                                <variable standardName="sea_surface_height"/>
                                
                            </variables>
                        </oostethys-netcdf>
                        
                    </sourceConfiguration>
                    
                    
                    
                    <variables>
                        <variable name="Time" uri="urn:ogc:phenomenon:time:iso8601" uom="hours since
                            2006-01-01 00:00 UTC" isTime="true" isCoordinate="true"/>
                        <variable name="longitude" uri="urn:ogc:phenomenon:longitude:wgs84" uom="degrees_east"/>
                        <variable name="latitude" uri="urn:ogc:phenomenon:latitude:wgs84" uom="degrees_north"/>
                        <variable name="sea_surface_height" uri="http://marinemetadata.org/cf#sea_surface_height" uom="meters"/>
                    </variables>
                    <values> 2008-06-05T04:30:00Z,42.20551,-70.72384,-1.01651 2008-06-05T05:30:00Z,42.20551,-70.72384,-1.761284 2008-06-05T06:30:00Z,42.20551,-70.72384,-2.052919 2008-06-05T07:30:00Z,42.20551,-70.72384,-1.811579 2008-06-05T08:30:00Z,42.20551,-70.72384,-1.114414 2008-06-05T09:30:00Z,42.20551,-70.72384,-0.151616 2008-06-05T10:30:00Z,42.20551,-70.72384,0.851955 2008-06-05T11:30:00Z,42.20551,-70.72384,1.641896 2008-06-05T12:30:00Z,42.20551,-70.72384,1.994201 2008-06-05T13:30:00Z,42.20551,-70.72384,1.843928 2008-06-05T14:30:00Z,42.20551,-70.72384,1.253456 2008-06-05T15:30:00Z,42.20551,-70.72384,0.370983 2008-06-05T16:30:00Z,42.20551,-70.72384,-0.621113 2008-06-05T17:30:00Z,42.20551,-70.72384,-1.475753 2008-06-05T18:30:00Z,42.20551,-70.72384,-1.951109 2008-06-05T19:30:00Z,42.20551,-70.72384,-1.923398 2008-06-05T20:30:00Z,42.20551,-70.72384,-1.406537 2008-06-05T21:30:00Z,42.20551,-70.72384,-0.548234 2008-06-05T22:30:00Z,42.20551,-70.72384,0.435682 2008-06-05T23:30:00Z,42.20551,-70.72384,1.319742</values>
                    </output>
                </system>
            </components>
            
          
        </system>

    </components>

</oostethys>

=== bermud/oostethys/trunk/component/server/java/oostethys-java-server/src/test/resources/oostethys-unc.xml
<?xml version="1.0" encoding="UTF-8"?>
<oostethys xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.oostethys.org/schemas/0.1.0/oostethys ../xml/oostethys/0.1.0/oostethys.xsd">

    <!-- 
    
    		This is an example OOSTethys configuration file, which takes a netcdf and makes available an SOS based on OOSTethys conventions. 
    		
    		OOSTehtys has components. Components are systems.  Systems could be observing systems, platforms, sensors , etc.
    		
    	    A System could contain components or output. 
    	    
    	    Output has sourceConfiguration - which in this case is a oostethys-netcdf configuration.
    	    
    	    oostethys-netcdf needs a URL of the file and the short name of the variables. The short name of the variable is the
    	    title of the variable that appears after the type when you see the header of a netcdf file or call the dump function.
    	    In the following example, the short name =  "Temp". This are unique within a file. 
    	    
    	    ...
    	     variables:
		   float Temp(esecs=8265, NominalDepth=1, Latitude=1, Longitude=1);
    		 :long_name = "Water Temperature";
		     :units = "deg C";
		     :standard_name = "Temperature";
		     
		     ...
		     
		     
    	If you have any problems please send an email to oostethys-support@lists.sourceforge.net
     -->


    <!--  This value is not neccesary. It will be filled by the web application. Leave it in blank -->
    <webServerURL/>

    <!--  SOS service metadata -->
    <serviceContact type="http://mmisw.org/mmi/20080520/obs.owl#serviceProvider" id="a1">
        <urlOrganization>http://nccoos.org</urlOrganization>
        <longNameOrganization>University of North Carolina at Chapel Hill</longNameOrganization>
        <shortNameOrganization>UNC-CH</shortNameOrganization>
        <individualName>Jesse Cleary</individualName>
        <individualEmail>jcleary@email.unc.edu</individualEmail>
    </serviceContact>

    <!--  Components could be observing systems, platforms, sensors , etc... -->
    <components>
        <system>
            <metadata>
                <sytemLongName>TWS Met station observation</sytemLongName>
                <systemShortName>jpier</systemShortName>
                <systemIdentifier>urn:unc:org:jpier</systemIdentifier>
                <systemType>http://mmisw.org/ont/Platform/metereologicalPlatform</systemType>
                <systemContacts>
                    <systemContact type="http://mmisw.org/mmi/20080520/obs.owl#dataProvider" id="c1">

                        <urlOrganization>http://nccoos.org</urlOrganization>
                        <longNameOrganization>University of North Carolina at Chapel Hill</longNameOrganization>
                        <shortNameOrganization>UNC-CH</shortNameOrganization>
                        <individualName>Jesse Cleary</individualName>
                        <individualEmail>jcleary@email.unc.edu</individualEmail>
                    </systemContact>
                </systemContacts>
            </metadata>

            <output>
                <sourceConfiguration>
                    <!--  source configuration is the information necessary to parse the NetCdf file  -->

                    <oostethys-netcdf xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">

                        <!--   URL of the NETCDF file or OPENDAP link. It could also be a relative path to
                                        the WEB_INF/classes folder in the web application -->

                        <fileURL>http://whewell.marine.unc.edu/data/nccoos/latest_v2.0/nccoos_jpier_met_latest.nc</fileURL>

                        <!--   ShortName of each variable. At least
				                             lat, lon and time coordinates should be given 
				                            -->

                        <variables>
                            <variable shortName="time"/>
                            <variable shortName="air_temp"/>
                            <variable shortName="wdir"/>
                            <variable shortName="air_pressure"/>
                            <variable shortName="humidity"/>
                            <variable shortName="wspd"/>
                            <variable shortName="lat"/>
                            <variable shortName="z"/>
                            <variable shortName="lon"/>
                            
                        </variables>
                    </oostethys-netcdf>
                </sourceConfiguration>
            </output>

        </system>


    </components>
</oostethys>
