=== bermud/oostethys/java/oostethys-java-server/src/main/resources/xml/oostethys/0.1.0/xsd/oostethys.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" targetNamespace="http://www.oostethys.org/schemas/0.1.0/oostethys"
	xmlns:oost="http://www.oostethys.org/schemas/0.1.0/oostethys"
	xmlns:oostcsv="http://www.oostethys.org/schemas/0.1.0/oostethys-csv"
	xmlns:oostnc="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">

	<xs:import namespace="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf"
		schemaLocation="oostethys-netcdf.xsd">
	</xs:import>
	<xs:import namespace="http://www.oostethys.org/schemas/0.1.0/oostethys-csv"
		schemaLocation="oostethys-csv.xsd">
	</xs:import>

	<xs:element name="oostethys">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="webServerURL" type="xs:string"
					minOccurs="0" />
				<xs:element ref="oost:serviceContact" />
				<xs:element ref="oost:components" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="systemContact">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="oost:contact">
					<xs:attribute name="ref" type="xs:IDREF" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="serviceContact">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="oost:contact">
				</xs:extension>
			</xs:complexContent>

		</xs:complexType>
	</xs:element>

	<xs:element name="referencedContact">
		<xs:complexType>
			<xs:attribute name="ref" type="xs:IDREF" />
		</xs:complexType>
	</xs:element>


	<xs:complexType name="contact">

		<xs:sequence>
			<xs:element name="urlOrganization" type="xs:anyURI" />
			<xs:element name="longNameOrganization" type="xs:string" />
			<xs:element name="shortNameOrganization" type="xs:string" />
			<xs:element name="individualName" type="xs:string" />
			<xs:element name="individualEmail" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="type" use="required" type="xs:anyURI" />
		<xs:attribute name="id" type="xs:ID" use="required" />

	</xs:complexType>



	<xs:element name="components">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:system" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="system">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:metadata" />
				<xs:element ref="oost:extend" minOccurs="0" />

				<!-- either has componenets or output -->
				<xs:choice>
					<xs:element ref="oost:components" />
					<xs:element ref="oost:output" />
				</xs:choice>
			</xs:sequence>

		</xs:complexType>
	</xs:element>

	<xs:element name="extend">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:timePeriod" minOccurs="0" />
				<xs:element ref="oost:boundingBox" minOccurs="0" />

			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="metadata">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="systemLongName" type="xs:string" />
				<xs:element name="systemShortName" type="xs:string" />
				<xs:element name="systemIdentifier" type="xs:anyURI" />
				<xs:element name="systemType" type="xs:anyURI" />
				<xs:element ref="oost:systemMetadataProperty" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element ref="oost:systemContacts" />
				<xs:element ref="oost:lastKnownLocation" minOccurs="0"
					maxOccurs="1">

				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="systemContacts">
		<xs:complexType>
			<xs:sequence minOccurs="1">
				<xs:element ref="oost:systemContact" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element ref="oost:referencedContact" minOccurs="0"
					maxOccurs="unbounded"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="lastKnownLocation">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="srsName" use="required"></xs:attribute>
				</xs:extension>
			</xs:simpleContent>


		</xs:complexType>


	</xs:element>

	<xs:element name="systemMetadataProperty">
		<xs:complexType>
			<xs:attribute name="propertyURI" type="xs:string" />
		</xs:complexType>
	</xs:element>


	<xs:element name="timePeriod">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="start" type="xs:string" />
				<xs:element name="end" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="endOfDeployment" type="xs:NMTOKEN" />
	<xs:element name="boundingBox">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:envelope" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="envelope">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:lowerCorner" />
				<xs:element ref="oost:upperCorner" />
			</xs:sequence>
			<xs:attribute name="srsName" use="required" type="xs:NMTOKEN" />
		</xs:complexType>
	</xs:element>
	<xs:element name="lowerCorner" type="xs:string" />
	<xs:element name="upperCorner" type="xs:string" />
	<xs:element name="url" type="xs:anyURI" />
	<xs:element name="nameOrganization" type="xs:string" />
	<xs:element name="shortNameOrganization" type="xs:NCName" />
	<xs:element name="individualName" type="xs:string" />
	<xs:element name="individualEmail" type="xs:string" />

	<xs:element name="output">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:sourceConfiguration" minOccurs="0" />
				<xs:element ref="oost:variables" minOccurs="0" />
				<xs:element ref="oost:values" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="sourceConfiguration">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="oostnc:oostethys-netcdf" />
				<xs:element ref="oostcsv:oostethys-csv" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="variables">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="oost:variable" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="variable">
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:string" />
			<xs:attribute name="uri" use="optional" type="xs:anyURI" />
			<xs:attribute name="uom" use="optional" type="xs:string" />
			<xs:attribute name="isCoordinate" use="optional" type="xs:boolean" />
			<xs:attribute name="isTime" use="optional" type="xs:boolean" />
			<xs:attribute name="referenceFrame" use="optional" type="xs:anyURI" />
		</xs:complexType>

	</xs:element>
	<xs:element name="values" type="xs:string" />


</xs:schema>

=== bermud/oostethys/java/oostethys-java-server/src/test/resources/mbariOostethys.xml
<?xml version="1.0" encoding="UTF-8"?>
<oostethys xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.oostethys.org/schemas/0.1.0/oostethys ../oostethys.xsd">

    <webServerURL>http://localhost:8080</webServerURL>
    <serviceContact type="http://mmisw.org/mmi/20080520/obs.owl#serviceProvider" id="a1">
        <urlOrganization>http://www.marinemetadata.org</urlOrganization>
        <longNameOrganization>Marine Metadata Interoperability Initiative (MMI)</longNameOrganization>
        <shortNameOrganization>MMI</shortNameOrganization>
        <individualName/>
        <individualEmail/>
    </serviceContact>
    <components>
        <system>
            <metadata>
                <systemLongName>Monterey Bay Aquarium Research Institute Observing System</systemLongName>
                <systemShortName>MBARI</systemShortName>
                <systemIdentifier>urn:mbari:org</systemIdentifier>
                <systemType>http://mmisw.org/mmi/20080520/obs.owl#observationSystem</systemType>
                <systemContacts>
                    <systemContact type="http://mmisw.org/mmi/20080520/obs.owl#dataProvider" id="c1">
                        <urlOrganization>http://www.mbari.org</urlOrganization>
                        <longNameOrganization>Monterey Bay Aquarium Research Institute</longNameOrganization>
                        <shortNameOrganization>MBARI</shortNameOrganization>
                        <individualName>John Graybeal</individualName>
                        <individualEmail>graybeal@mbari.org</individualEmail>
                    </systemContact>
                </systemContacts>
            </metadata>
            <components>
                <system>
                    <metadata>
                        <systemLongName>Mooring M2</systemLongName>
                        <systemShortName>m2</systemShortName>
                        <systemIdentifier>uri:mbari:org:mooring:m2</systemIdentifier>
                        <systemType>http://mmisw.org/mmi/20080516/platform#MooredBuoy</systemType>
                        <systemContacts/>
                    </metadata>
                    <components>
                        <system>
                            <metadata>
                                <systemLongName>Serial CTD</systemLongName>
                                <systemShortName>1455</systemShortName>
                                <systemIdentifier>urn:mbari:org:device:1455</systemIdentifier>
                                <systemType>http://mmisw.org/mmi/20080529/sensor.owl#CTD</systemType>
                                <systemContacts/>
                            </metadata>
                            <output>
                                <sourceConfiguration>
                                    <oostethys-netcdf
                                        xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
                                        <fileURL>http://dods.mbari.org/cgi-bin/nph-nc/data/ssdsdata/deployments/m2/200804/m2_ctd0010_20080411_original.nc</fileURL>
                                        <variables>
                                            <variable standardName="time GMT"/>
                                            <variable standardName="longitude"/>
                                            <variable standardName="latitude"/>
                                            <variable standardName="depth"/>
                                            <variable standardName="Temperature"/>
                                            <variable standardName="Conductivity"/>
                                            <variable standardName="Pressure"/>
                                        </variables>
                                    </oostethys-netcdf>
                                </sourceConfiguration>
                            </output>
                        </system>
                        <system>
                            <metadata>
                                <systemLongName>Aanderaa Oxygen Optode (aanderaaoxy) </systemLongName>
                                <systemShortName>1595</systemShortName>
                                <systemIdentifier>urn:mbari:org:device:1595</systemIdentifier>
                                <systemType>http://mmisw.org/mmi/20080529/sensor.owl#OxygenSensor</systemType>
                                <systemContacts></systemContacts>
                            </metadata>
                       
                        <output>
                            <sourceConfiguration>
                                <oostethys-netcdf
                                    xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
                                    <fileURL>http://dods.mbari.org/cgi-bin/nph-nc/data/ssdsdata/deployments/m2/200804/m2_aanderaaoxy_20080411.nc</fileURL>
                                    <variables>
                                        <variable standardName="time GMT"/>
                                        <variable standardName="longitude"/>
                                        <variable standardName="latitude"/>
                                        <variable standardName="depth"/>
                                        <variable standardName="checkString"/>
                                        <variable standardName="Oxygen"/>
                                        <variable standardName="OxygenAirSaturation"/>
                                        <variable standardName="temperature"/>
                                    </variables>
                                </oostethys-netcdf>
                            </sourceConfiguration>
                        </output>
                        </system>
                    </components>
                </system>
            </components>
        </system>
    </components>
</oostethys>

=== bermud/oostethys/java/oostethys-java-server/src/main/resources/xml/oostethys/0.1.0/example/mbari-oost.xml
<?xml version="1.0" encoding="UTF-8"?>
<oostethys xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.oostethys.org/schemas/0.1.0/oostethys ../oostethys.xsd">

    <webServerURL>http://localhost:8080</webServerURL>
    <serviceContact type="http://mmisw.org/mmi/20080520/obs.owl#serviceProvider" id="a1">
        <urlOrganization>http://www.marinemetadata.org</urlOrganization>
        <longNameOrganization>Marine Metadata Interoperability Initiative (MMI)</longNameOrganization>
        <shortNameOrganization>MMI</shortNameOrganization>
        <individualName/>
        <individualEmail/>
    </serviceContact>
    <components>
        <system>
            <metadata>
                <systemLongName>Monterey Bay Aquarium Research Institute Observing System</systemLongName>
                <systemShortName>MBARI</systemShortName>
                <systemIdentifier>urn:mbari:org</systemIdentifier>
                <systemType>http://mmisw.org/mmi/20080520/obs.owl#observationSystem</systemType>
                <systemContacts>
                    <systemContact type="http://mmisw.org/mmi/20080520/obs.owl#dataProvider" id="c1">
                        <urlOrganization>http://www.mbari.org</urlOrganization>
                        <longNameOrganization>Monterey Bay Aquarium Research Institute</longNameOrganization>
                        <shortNameOrganization>MBARI</shortNameOrganization>
                        <individualName>Firstname lastName</individualName>
                        <individualEmail>zzx@xxx.org</individualEmail>
                    </systemContact>
                </systemContacts>
            </metadata>
            <components>
                <system>
                    <metadata>
                        <systemLongName>Mooring M2</systemLongName>
                        <systemShortName>m2</systemShortName>
                        <systemIdentifier>uri:mbari:org:mooring:m2</systemIdentifier>
                        <systemType>http://mmisw.org/mmi/20080516/platform#MooredBuoy</systemType>
                        <systemContacts/>
                    </metadata>
                    <components>
                        <system>
                            <metadata>
                                <systemLongName>Serial CTD</systemLongName>
                                <systemShortName>1455</systemShortName>
                                <systemIdentifier>urn:mbari:org:device:1455</systemIdentifier>
                                <systemType>http://mmisw.org/mmi/20080529/sensor.owl#CTD</systemType>
                                <systemContacts/>
                            </metadata>
                            <output>
                                <sourceConfiguration>
                                    <oostethys-netcdf
                                        xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
                                        <fileURL>ctd0010.nc</fileURL>
                                        <variables>
                                            <variable shortName="esecs"/>
                                            <variable shortName="Longitude"/>
                                            <variable shortName="Latitude"/>
                                            <variable shortName="NominalDepth"/>
                                            <variable shortName="Temperature"/>
                                            <variable shortName="Conductivity"/>
                                            <variable shortName="Pressure"/>
                                            <variable shortName="Salinity"/>
                                        </variables>
                                    </oostethys-netcdf>
                                </sourceConfiguration>
                            </output>
                        </system>
                        
                    </components>
                </system>
            </components>
        </system>
    </components>
</oostethys>

=== bermud/oostethys/java/oostethys-java-server/src/test/resources/oostethys-roym.xml
<?xml version="1.0" encoding="UTF-8"?>
<oostethys xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.oostethys.org/schemas/0.1.0/oostethys ../../main/resources/xml/oostethys/0.1.0/xsd/oostethys.xsd">
	
	<webServerURL>http://localhost:8080</webServerURL>
	<serviceContact
		type="http://mmisw.org/mmi/20080520/obs.owl#serviceProvider"
		id="a1">
		<urlOrganization>http://www.pfel.noaa.gov</urlOrganization>
		<longNameOrganization>
			NOAA/NMFS/SWFSC Environmental Research Division
		</longNameOrganization>
		<shortNameOrganization>ERD</shortNameOrganization>
		<individualName />
		<individualEmail />
	</serviceContact>
	
	<components>
		<system>
			<metadata>
				<systemLongName>Coastwatch Monthly SST Blended, Global, Experimental</systemLongName>
				<systemShortName>aggregsatBA_sstamday</systemShortName>
				<systemIdentifier>urn:usgs:gov:model:um1-gom</systemIdentifier>
				<systemType>
					http://mmisw.org/mmi/platform#Satellite
				</systemType>
				<systemContacts>
					<systemContact
						type="http://mmisw.org/mmi/20080520/obs.owl#dataProvider"
						id="c1">
						<urlOrganization>
							org
						</urlOrganization>
						<longNameOrganization>
							a long name
						</longNameOrganization>
						<shortNameOrganization>
							shortName
						</shortNameOrganization>
						<individualName>FirstName lastName</individualName>
						<individualEmail>xxx@xxx.org</individualEmail>
					</systemContact>
				</systemContacts>
			</metadata>
			
			
			<output>
				
				<sourceConfiguration>
					<oostethys-netcdf
						xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
						<fileURL>
							http://localhost:21983/oceanwatch.pfeg.noaa.gov/thredds/dodsC/satellite/BA/ssta/mday
						</fileURL>
						
						
							
						<variables>
							<variable shortName="altitude" dimension="depth" uri="http://mmisw.org/ont/cf/parameter/depth"/>
							<variable shortName="lat"  dimension="latitude" uri="urn:ogc:phenomenon:latitude:wgs84" />
							<variable shortName="lon" dimension="longitude" uri="urn:ogc:phenomenon:longitude:wgs84"/>
							<variable shortName="time"  dimension="time" uri="http://mmisw.org/ont/cf/parameter/iso_19118_time" />
							<variable shortName="BAssta" dimension="no" uri="http://mmisw.org/ont/cf/parameter/sea_water_temperature"/>
							
						</variables>
					</oostethys-netcdf>
					
					
				</sourceConfiguration>
				
			</output>
		</system>
		<system>
			<metadata>
				<systemLongName> Coastwatch 8day Primary Productivity Experimental</systemLongName>
				<systemShortName>aggregsatPN_bfp28day</systemShortName>
				<systemIdentifier>urn:usgs:gov:model:fvcom-gom</systemIdentifier>
				<systemType>http://mmisw.org/mmi/platform#Satellite </systemType>
				<systemContacts>
					<referencedContact ref="a1"/>
					
				</systemContacts>
			</metadata>
			
			
			
			<output>
				
				<sourceConfiguration>
					
					<oostethys-netcdf
						xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
						<fileURL> http://localhost:21983/oceanwatch.pfeg.noaa.gov/thredds/dodsC/satellite/PN/bfp2/8day </fileURL>
						
						<variables>
							<variable shortName="altitude" dimension="depth" uri="http://mmisw.org/ont/cf/parameter/depth"/>
							<variable shortName="lat"  dimension="latitude" uri="urn:ogc:phenomenon:latitude:wgs84" />
							<variable shortName="lon" dimension="longitude" uri="urn:ogc:phenomenon:longitude:wgs84"/>
							<variable shortName="time"  dimension="time" uri="http://mmisw.org/ont/cf/parameter/iso_19118_time" />
						
							<variable shortName="PNbfp2" dimension="no" uri="urn:no:no"  />
							
						</variables>
					</oostethys-netcdf>
					
				</sourceConfiguration>
				
			</output>
		</system>
		
	</components>
	
</oostethys>

=== bermud/oostethys/java/oostethys-java-server/src/main/resources/xml/oostethys/0.1.0/example/usmass-oost.xml
<?xml version="1.0" encoding="UTF-8"?>
<oostethys xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.oostethys.org/schemas/0.1.0/oostethys ../oostethys.xsd">

	<webServerURL>http://localhost:8080</webServerURL>
	<serviceContact
		type="http://mmisw.org/mmi/20080520/obs.owl#serviceProvider"
		id="a1">
		<urlOrganization>http://www.marinemetadata.org</urlOrganization>
		<longNameOrganization>
			Marine Metadata Interoperability Initiative (MMI)
		</longNameOrganization>
		<shortNameOrganization>MMI</shortNameOrganization>
		<individualName />
		<individualEmail />
	</serviceContact>

	<components>
		<system>
			<metadata>
				<systemLongName>xxx Model</systemLongName>
				<systemShortName>um</systemShortName>
				<systemIdentifier>urn:xxx:org:model1</systemIdentifier>
				<systemType>
					http://mmisw.org/mmi/20080520/obs.owl#numericalModel
				</systemType>
				<systemContacts>
					<systemContact
						type="http://mmisw.org/mmi/20080520/obs.owl#dataProvider"
						id="c1">
						<urlOrganization>
							org
						</urlOrganization>
						<longNameOrganization>
							a long name
						</longNameOrganization>
						<shortNameOrganization>
							shortName
						</shortNameOrganization>
						<individualName>FirtName lastName</individualName>
						<individualEmail>xxx@xxx.org</individualEmail>
					</systemContact>
				</systemContacts>
			</metadata>



			<output>

				<sourceConfiguration>
					<oostethys-netcdf
						xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
						<fileURL>
							umassb_scituate.nc
						</fileURL>

						<variables>
							<variable shortName="lat" />
							<variable shortName="lon" />
							<variable shortName="time" />
							<variable shortName="elev" />

						</variables>
					</oostethys-netcdf>

				</sourceConfiguration>

			</output>
		</system>

	</components>

</oostethys>

=== bermud/oostethys/trunk/component/server/java/src/test/oostethys_notfoundvars.xml
<?xml version="1.0" encoding="UTF-8"?>
<oostethys xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.oostethys.org/schemas/0.1.0/oostethys http://www.oostethys.org/schemas/0.1.0/oostethys.xsd">

	<webServerURL>http://coast-enviro.er.usgs.gov</webServerURL>
	<serviceContact type="http://mmisw.org/mmi/20080520/obs.owl#serviceProvider" id="a1">
		<urlOrganization>http://www.marinemetadata.org</urlOrganization>
		<longNameOrganization> Marine Metadata Interoperability Initiative (MMI) </longNameOrganization>
		<shortNameOrganization>MMI</shortNameOrganization>
		<individualName/>
		<individualEmail/>
	</serviceContact>

	<components>
		<system>
			<metadata>
			<!--  this tag is not correct -->
		
				<sytemLongName>xxx Model</sytemLongName>
				<systemShortName>um</systemShortName>
				<systemIdentifier>urn:xxx:org:model1</systemIdentifier>
				<systemType> http://mmisw.org/mmi/20080520/obs.owl#numericalModel </systemType>
				<systemContacts>
					<systemContact type="http://mmisw.org/mmi/20080520/obs.owl#dataProvider" id="c1">
						<urlOrganization> org </urlOrganization>
						<longNameOrganization> a long name </longNameOrganization>
						<shortNameOrganization> shortName </shortNameOrganization>
						<individualName>FirtName lastName</individualName>
						<individualEmail>xxx@xxx.org</individualEmail>
					</systemContact>
				</systemContacts>
				
			</metadata>



			<output>

				<sourceConfiguration>
					<oostethys-netcdf
						xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
						<fileURL>
							file:test/ctd0010.nc</fileURL>

						<variables>
							<variable shortName="Latitu"/>
							<variable shortName="Lonitude"/>
							<variable shortName="esecs"/>
							<variable shortName="Salinity"/>

						</variables>
					</oostethys-netcdf>


				</sourceConfiguration>

			</output>
		</system>
		
	</components>

</oostethys>
