=== bermud/oostethys/java/oostethys-java-server/src/main/resources/xml/oostethys/0.1.0/xsd/oostethys.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" targetNamespace="http://www.oostethys.org/schemas/0.1.0/oostethys"
	xmlns:oost="http://www.oostethys.org/schemas/0.1.0/oostethys"
	xmlns:oostcsv="http://www.oostethys.org/schemas/0.1.0/oostethys-csv"
	xmlns:oostnc="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">

	<xs:import namespace="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf"
		schemaLocation="oostethys-netcdf.xsd">
	</xs:import>
	<xs:import namespace="http://www.oostethys.org/schemas/0.1.0/oostethys-csv"
		schemaLocation="oostethys-csv.xsd">
	</xs:import>

	<xs:element name="oostethys">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="webServerURL" type="xs:string"
					minOccurs="0" />
				<xs:element ref="oost:serviceContact" />
				<xs:element ref="oost:components" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="systemContact">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="oost:contact">
					<xs:attribute name="ref" type="xs:IDREF" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="serviceContact">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="oost:contact">
				</xs:extension>
			</xs:complexContent>

		</xs:complexType>
	</xs:element>

	<xs:element name="referencedContact">
		<xs:complexType>
			<xs:attribute name="ref" type="xs:IDREF" />
		</xs:complexType>
	</xs:element>


	<xs:complexType name="contact">

		<xs:sequence>
			<xs:element name="urlOrganization" type="xs:anyURI" />
			<xs:element name="longNameOrganization" type="xs:string" />
			<xs:element name="shortNameOrganization" type="xs:string" />
			<xs:element name="individualName" type="xs:string" />
			<xs:element name="individualEmail" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="type" use="required" type="xs:anyURI" />
		<xs:attribute name="id" type="xs:ID" use="required" />

	</xs:complexType>



	<xs:element name="components">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:system" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="system">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:metadata" />
				<xs:element ref="oost:extend" minOccurs="0" />

				<!-- either has componenets or output -->
				<xs:choice>
					<xs:element ref="oost:components" />
					<xs:element ref="oost:output" />
				</xs:choice>
			</xs:sequence>

		</xs:complexType>
	</xs:element>

	<xs:element name="extend">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:timePeriod" minOccurs="0" />
				<xs:element ref="oost:boundingBox" minOccurs="0" />

			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="metadata">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="systemLongName" type="xs:string" />
				<xs:element name="systemShortName" type="xs:string" />
				<xs:element name="systemIdentifier" type="xs:anyURI" />
				<xs:element name="systemType" type="xs:anyURI" />
				<xs:element ref="oost:systemMetadataProperty" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element ref="oost:systemContacts" />
				<xs:element ref="oost:lastKnownLocation" minOccurs="0"
					maxOccurs="1">

				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="systemContacts">
		<xs:complexType>
			<xs:sequence minOccurs="1">
				<xs:element ref="oost:systemContact" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element ref="oost:referencedContact" minOccurs="0"
					maxOccurs="unbounded"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="lastKnownLocation">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="srsName" use="required"></xs:attribute>
				</xs:extension>
			</xs:simpleContent>


		</xs:complexType>


	</xs:element>

	<xs:element name="systemMetadataProperty">
		<xs:complexType>
			<xs:attribute name="propertyURI" type="xs:string" />
		</xs:complexType>
	</xs:element>


	<xs:element name="timePeriod">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="start" type="xs:string" />
				<xs:element name="end" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="endOfDeployment" type="xs:NMTOKEN" />
	<xs:element name="boundingBox">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:envelope" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="envelope">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:lowerCorner" />
				<xs:element ref="oost:upperCorner" />
			</xs:sequence>
			<xs:attribute name="srsName" use="required" type="xs:NMTOKEN" />
		</xs:complexType>
	</xs:element>
	<xs:element name="lowerCorner" type="xs:string" />
	<xs:element name="upperCorner" type="xs:string" />
	<xs:element name="url" type="xs:anyURI" />
	<xs:element name="nameOrganization" type="xs:string" />
	<xs:element name="shortNameOrganization" type="xs:NCName" />
	<xs:element name="individualName" type="xs:string" />
	<xs:element name="individualEmail" type="xs:string" />

	<xs:element name="output">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="oost:sourceConfiguration" minOccurs="0" />
				<xs:element ref="oost:variables" minOccurs="0" />
				<xs:element ref="oost:values" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="sourceConfiguration">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="oostnc:oostethys-netcdf" />
				<xs:element ref="oostcsv:oostethys-csv" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="variables">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="oost:variable" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="variable">
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:string" />
			<xs:attribute name="uri" use="optional" type="xs:anyURI" />
			<xs:attribute name="uom" use="optional" type="xs:string" />
			<xs:attribute name="isCoordinate" use="optional" type="xs:boolean" />
			<xs:attribute name="isTime" use="optional" type="xs:boolean" />
			<xs:attribute name="referenceFrame" use="optional" type="xs:anyURI" />
		</xs:complexType>

	</xs:element>
	<xs:element name="values" type="xs:string" />


</xs:schema>

=== bermud/oostethys/component/server/java/oostethys-java-server/src/test/resources/oostethys2.xml
<?xml version="1.0" encoding="UTF-8"?>
<oos:oostethys
    xmlns:oos="http://www.oostethys.org/schemas/0.1.0/oostethys"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.oostethys.org/schemas/0.1.0/oostethys file:/Users/bermudez/Documents/workspace31/oostethys-xml/oostethys/0.1.0/oostethys.xsd">
    <oos:serviceContact
        type="http://mmisw.org/mmi/20080520/obs.owl#serviceProvider" id="a1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <oos:urlOrganization>
            http://www.marinemetadata.org
        </oos:urlOrganization>
        <oos:longNameOrganization>
            Marine Metadata Interoperability Initiative (MMI)
        </oos:longNameOrganization>
        <oos:shortNameOrganization>MMI</oos:shortNameOrganization>
        <oos:individualName />
        <oos:individualEmail />
    </oos:serviceContact>
    <oos:components>
        <oos:system>
            <oos:metadata
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                <oos:systemLongName>USGS Model</oos:systemLongName>
                <oos:systemShortName>um</oos:systemShortName>
                <oos:systemIdentifier>
                    urn:usgs:org:model1
                </oos:systemIdentifier>
                <oos:systemType>
                    http://mmisw.org/mmi/20080520/obs.owl#numericalModel
                </oos:systemType>
                
                <oos:systemContacts>
                    <oos:systemContact
                        type="http://mmisw.org/mmi/20080520/obs.owl#dataProvider"
                        id="c1">
                        <oos:urlOrganization>
                            http://www.usgs.org
                        </oos:urlOrganization>
                        <oos:longNameOrganization>
                            USGS
                        </oos:longNameOrganization>
                        <oos:shortNameOrganization>
                            USGS
                        </oos:shortNameOrganization>
                        <oos:individualName>
                            Rick Ludich
                        </oos:individualName>
                        <oos:individualEmail>
                            r@usgs.org
                        </oos:individualEmail>
                    </oos:systemContact>
                </oos:systemContacts>
                <oos:lastKnownLocation srsName="urn:ogc:def:crs:EPSG:6.5:4326">
                    42.20551 -70.72384
                </oos:lastKnownLocation>
            </oos:metadata>
            <oos:extend>
                <oos:timePeriod>
                    <oos:start>2008-06-05T04:30:00Z</oos:start>
                    <oos:end>2008-06-05T23:30:00Z</oos:end>
                </oos:timePeriod>
                <oos:boundingBox>
                    <oos:envelope srsName="urn:ogc:def:crs:EPSG:6.5:4326">
                        <oos:lowerCorner>
                            42.20551 -70.72384
                        </oos:lowerCorner>
                        <oos:upperCorner>
                            42.20551 -70.72384
                        </oos:upperCorner>
                    </oos:envelope>
                </oos:boundingBox>
                
            </oos:extend>
            
            <oos:output>
                <oos:variables>
                    <oos:variable uri="urn:ogc:phenomenon:time:iso8601"
                        name="Time" uom="hours since 2006-01-01 00:00 UTC"
                        isCoordinate="true" isTime="true" />
                    <oos:variable
                        uri="urn:ogc:phenomenon:latitude:wgs84" name="latitude"
                        uom="degrees_north" isCoordinate="true" />
                    <oos:variable
                        uri="urn:ogc:phenomenon:longitude:wgs84" name="longitude"
                        uom="degrees_east" isCoordinate="true" />
                    <oos:variable
                        uri="http://marinemetadata.org/cf#sea_surface_height"
                        name="sea_surface_height" uom="" isCoordinate="false" />
                </oos:variables>
                <oos:values>
                    2008-06-05T04:30:00Z,42.20551,-70.72384,-1.01651
                    2008-06-05T05:30:00Z,42.20551,-70.72384,-1.761284
                    2008-06-05T06:30:00Z,42.20551,-70.72384,-2.052919
                    2008-06-05T07:30:00Z,42.20551,-70.72384,-1.811579
                    2008-06-05T08:30:00Z,42.20551,-70.72384,-1.114414
                    2008-06-05T09:30:00Z,42.20551,-70.72384,-0.151616
                    2008-06-05T10:30:00Z,42.20551,-70.72384,0.851955
                    2008-06-05T11:30:00Z,42.20551,-70.72384,1.641896
                    2008-06-05T12:30:00Z,42.20551,-70.72384,1.994201
                    2008-06-05T13:30:00Z,42.20551,-70.72384,1.843928
                    2008-06-05T14:30:00Z,42.20551,-70.72384,1.253456
                    2008-06-05T15:30:00Z,42.20551,-70.72384,0.370983
                    2008-06-05T16:30:00Z,42.20551,-70.72384,-0.621113
                    2008-06-05T17:30:00Z,42.20551,-70.72384,-1.475753
                    2008-06-05T18:30:00Z,42.20551,-70.72384,-1.951109
                    2008-06-05T19:30:00Z,42.20551,-70.72384,-1.923398
                    2008-06-05T20:30:00Z,42.20551,-70.72384,-1.406537
                    2008-06-05T21:30:00Z,42.20551,-70.72384,-0.548234
                    2008-06-05T22:30:00Z,42.20551,-70.72384,0.435682
                    2008-06-05T23:30:00Z,42.20551,-70.72384,1.319742
                </oos:values>
            </oos:output>
        </oos:system>
    </oos:components>
</oos:oostethys>

=== bermud/oostethys/branches/oostethys-java-server_0.4.3_r413_2009-12-15T2151-0500/java/oostethys-java-server/src/test/resources/oostethys_issue_51.xml
<?xml version="1.0" encoding="UTF-8"?>
<oostethys xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.oostethys.org/schemas/0.1.0/oostethys ../../main/resources/xml/oostethys/0.1.0/xsd/oostethys.xsd">

  <webServerURL>http://coast-enviro.er.usgs.gov</webServerURL>
  <serviceContact type="http://mmisw.org/mmi/20080520/obs.owl#serviceProvider" id="contact">
    <urlOrganization>http://www.usgs.gov</urlOrganization>
    <longNameOrganization> USGS</longNameOrganization>
    <shortNameOrganization>usgs</shortNameOrganization>
    <individualName>Rich Signell</individualName>
    <individualEmail>rsignll@usgs.gov</individualEmail>
  </serviceContact>

  <components>
    <system>
      <metadata>
        <systemLongName>NECOFS Sea Surface Height at Scituate</systemLongName>
        <systemShortName>necofs</systemShortName>
        <systemIdentifier>urn:usgs:org:model:necofs</systemIdentifier>
        <systemType> http://mmisw.org/mmi/20080520/obs.owl#numericalModel </systemType>
        <systemContacts>
          <referencedContact ref="contact"/>
        </systemContacts>
      </metadata>
      <output>

        <sourceConfiguration>
          <oostethys-netcdf xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
            <fileURL>
              http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_FVCOM_OCEAN_MASSBAY_FORECAST.nc.dods?lon[28482],lat[28482],time[0:71],zeta[0:71][28482]
            </fileURL>
            <variables>
              <variable shortName="lat" dimension="latitude" uri="urn:ogc:phenomenon:latitude:wgs84"/>
              <variable shortName="lon" dimension="longitude" uri="urn:ogc:phenomenon:longitude:wgs84"/>
              <variable shortName="time" dimension="time" uri="urn:ogc:phenomenon:time:iso8601"/>
              <variable shortName="zeta" dimension="no" uri="urn:x:d"/>
            </variables>
          </oostethys-netcdf>
        </sourceConfiguration>

      </output>
    </system>

    <system>
      <metadata>
        <systemLongName>WW3 Significant Wave Height at Scituate</systemLongName>
        <systemShortName>ww3</systemShortName>
        <systemIdentifier>urn:usgs:org:model:necofs</systemIdentifier>
        <systemType> http://mmisw.org/mmi/20080520/obs.owl#numericalModel </systemType>
        <systemContacts>
          <referencedContact ref="contact"/>
        </systemContacts>
      </metadata>
      <output>
        
        <sourceConfiguration>
          <oostethys-netcdf xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
            <fileURL>
              http://coast-enviro.er.usgs.gov/thredds/dodsC/gom_interop/bio/ww3/forecast/fine.dods?lon[13],lat[38],time[0:48],hs[0:48][38][13]
            </fileURL>
            <variables>
              <variable shortName="lat" dimension="latitude" uri="urn:ogc:phenomenon:latitude:wgs84"/>
              <variable shortName="lon" dimension="longitude" uri="urn:ogc:phenomenon:longitude:wgs84"/>
              <variable shortName="time" dimension="time" uri="urn:ogc:phenomenon:time:iso8601"/>
              <variable shortName="hs" dimension="no" uri="urn:x:d"/>
            </variables>
          </oostethys-netcdf>
        </sourceConfiguration>
        
      </output>
    </system>
  </components>

</oostethys>

=== bermud/oostethys/branches/oostethys-java-server_0.4.3_r413_2009-12-15T2151-0500/java/oostethys-java-server/src/test/resources/ostethys_emptyString2.xml
<?xml version="1.0" encoding="UTF-8"?>
<oostethys xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.oostethys.org/schemas/0.1.0/oostethys
	http://www.oostethys.org/schemas/0.1.0/oostethys.xsd">
	
	<webServerURL>http://localhost:8080</webServerURL>
	<serviceContact
		type="http://mmisw.org/mmi/20080520/obs.owl#serviceProvider"
		id="a1">
		<urlOrganization>http://usgs.gov</urlOrganization>
		<longNameOrganization>
			USGS
		</longNameOrganization>
		<shortNameOrganization>usgs</shortNameOrganization>
		<individualName />
		<individualEmail />
	</serviceContact>
	
	<components>
		<system>
			<metadata>
				<systemLongName> Model umassb_scituate - GOM</systemLongName>
				<systemShortName>um1</systemShortName>
				<systemIdentifier>urn:usgs:gov:model:um1-gom</systemIdentifier>
				<systemType>
					http://mmisw.org/mmi/20080520/obs.owl#numericalModel
				</systemType>
				<systemContacts>
					<systemContact
						type="http://mmisw.org/mmi/20080520/obs.owl#dataProvider"
						id="c1">
						<urlOrganization>
							org
						</urlOrganization>
						<longNameOrganization>
							a long name
						</longNameOrganization>
						<shortNameOrganization>
							shortName
						</shortNameOrganization>
						<individualName>FirstName lastName</individualName>
						<individualEmail>xxx@xxx.org</individualEmail>
					</systemContact>
				</systemContacts>
			</metadata>
			
			
			<output>
				
				<sourceConfiguration>
					<oostethys-netcdf
						xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
						<fileURL>
							http://coast-enviro.er.usgs.gov/cgi-bin/nph-dods/models/gom_interop/umassb_scituate.nc
						</fileURL>
						
						<variables>
							<variable shortName="lat" />
							<variable shortName="lon" />
							<variable shortName="time" />
							<variable shortName="elev" />
							
						</variables>
					</oostethys-netcdf>
					
					
				</sourceConfiguration>
				
			</output>
		</system>
		<system>
			<metadata>
				<systemLongName> Model FVCOM - USGS - GOM</systemLongName>
				<systemShortName>um2</systemShortName>
				<systemIdentifier>urn:usgs:gov:model:fvcom-gom</systemIdentifier>
				<systemType> http://mmisw.org/mmi/20080520/obs.owl#numericalModel </systemType>
				<systemContacts>
					<referencedContact ref="a1"/>
					
				</systemContacts>
			</metadata>
			
			
			
			<output>
				
				<sourceConfiguration>
					
					<oostethys-netcdf
						xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
						<fileURL> http://coast-enviro.er.usgs.gov/thredds/dodsC/fvcom/scituate </fileURL>
						
						<variables>
							<variable shortName="lat"/>
							<variable shortName="lon"/>
							<variable shortName="time"/>
							<variable shortName="zeta"/>
							
						</variables>
					</oostethys-netcdf>
					
				</sourceConfiguration>
				
			</output>
		</system>
		
	</components>
	
</oostethys>

=== bermud/oostethys/branches/without_maven/component/server/java/src/test/oostethys-18.xml
<?xml version="1.0" encoding="UTF-8"?>
<oostethys xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.oostethys.org/schemas/0.1.0/oostethys ../xml/oostethys/0.1.0/oostethys.xsd">
    
    <!-- 
    
    		This is an example OOSTethys configuration file, which takes a netcdf and makes available an SOS based on OOSTethys conventions. 
    		
    		OOSTehtys has components. Components are systems.  Systems could be observing systems, platforms, sensors , etc.
    		
    	    A System could contain components or output. 
    	    
    	    Output has sourceConfiguration - which in this case is a oostethys-netcdf configuration.
    	    
    	    oostethys-netcdf needs a URL of the file and the short name of the variables. The short name of the variable is the
    	    title of the variable that appears after the type when you see the header of a netcdf file or call the dump function.
    	    In the following example, the short name =  "Temp". This are unique within a file. 
    	    
    	    ...
    	     variables:
		   float Temp(esecs=8265, NominalDepth=1, Latitude=1, Longitude=1);
    		 :long_name = "Water Temperature";
		     :units = "deg C";
		     :standard_name = "Temperature";
		     
		     ...
		     
		     
    	If you have any problems please send an email to oostethys-support@lists.sourceforge.net
     -->
    

<!--  This value is not neccesary. It will be filled by the web application. Leave it in blank -->
    <webServerURL></webServerURL>
    
    <!--  SOS service metadata -->
    <serviceContact type="http://mmisw.org/mmi/20080520/obs.owl#serviceProvider" id="a1">
        <urlOrganization>http://www.marinemetadata.org</urlOrganization>
        <longNameOrganization>Marine Metadata Interoperability Initiative (MMI)</longNameOrganization>
        <shortNameOrganization>MMI</shortNameOrganization>
        <individualName></individualName>
        <individualEmail></individualEmail>
    </serviceContact>
    
    <!--  Components could be observing systems, platforms, sensors , etc... -->
    <components>
        <system>
            <metadata>
                <sytemLongName>Monterey Bay Aquarium Research Institute Observing System</sytemLongName>
                <systemShortName>MBARI</systemShortName>
                <systemIdentifier>urn:mbari:org</systemIdentifier>
                <systemType>http://mmisw.org/mmi/20080520/obs.owl#observationSystem</systemType>
                <systemContacts>
                    <systemContact type="http://mmisw.org/mmi/20080520/obs.owl#dataProvider" id="c1">
                        <urlOrganization>http://www.mbari.org</urlOrganization>
                        <longNameOrganization>Monterey Bay Aquarium Research Institute</longNameOrganization>
                        <shortNameOrganization>MBARI</shortNameOrganization>
                        <individualName>John G</individualName>
                        <individualEmail>xxx@yyy.org</individualEmail>
                    </systemContact>
                </systemContacts>
            </metadata>
            
            <!--  A System could contain components or output.  -->
            
            <components>
                <system>
                   <metadata>
                        <sytemLongName>Mooring M0</sytemLongName>
                        <systemShortName>m0</systemShortName>
                        <systemIdentifier>uri:mbari:org:mooring:m0</systemIdentifier>
                        <systemType>http://mmisw.org/mmi/20080516/platform#MooredBuoy</systemType>
                        <systemContacts/>
                    </metadata>
                    <components>
                        <system>
                        
                          <!--  This system has outputs and no components -->
                          
                            <metadata>
                                <sytemLongName>Serial CTD</sytemLongName>
                                <systemShortName>1455</systemShortName>
                                <systemIdentifier>urn:mbari:org:device:1455</systemIdentifier>
                                <systemType>http://mmisw.org/mmi/20080529/sensor.owl#CTD</systemType>
                                <systemContacts/>
                            </metadata>
                            <output>
                                <sourceConfiguration>
                                   <!--  source configuration is the information necessary to parse the NetCdf file  -->
                            
                                    <oostethys-netcdf
                                        xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
                                        
                                        <!--   URL of the NETCDF file or OPENDAP link. It could also be a relative path to
                                        the WEB_INF/classes folder in the web application -->
                                        
                                        <fileURL>http://dods.mbari.org/cgi-bin/nph-nc/data/ssdsdata/deployments/m0/200607/hourlyM0_20060731.nc</fileURL>
                                        
		                                  <!--   ShortName of each variable. At least
				                             lat, lon and time coordinates should be given 
				                            -->
                                        
                                        <variables>
                                            <variable shortName="LONGITUDE"/>
                                            <variable shortName="LATITUDE"/>
                                            <variable shortName="HR_TIME_ADCP"/>
                                            <variable shortName="HR_DEPTH_ADCP"/>
                                        </variables>
                                    </oostethys-netcdf>
                                </sourceConfiguration>
                            </output>
                        </system>
                        
                    </components>
                </system>
               
            </components>
        </system>
    </components>
</oostethys>

=== bermud/oostethys/branches/ea/oostethys-java-server_0.4.0_r299_2009-10-13T1444-0400/oostethys-java-server/src/test/resources/oostethys-opendap.xml
<?xml version="1.0" encoding="UTF-8"?>
<oostethys xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://www.oostethys.org/schemas/0.1.0/oostethys ../../main/resources/xml/oostethys/0.1.0/xsd/oostethys.xsd">

	<webServerURL>http://coast-enviro.er.usgs.gov</webServerURL>
	<serviceContact type="http://mmisw.org/mmi/20080520/obs.owl#serviceProvider" id="a1">
		<urlOrganization>http://www.marinemetadata.org</urlOrganization>
		<longNameOrganization> Marine Metadata Interoperability Initiative (MMI) </longNameOrganization>
		<shortNameOrganization>MMI</shortNameOrganization>
		<individualName/>
		<individualEmail/>
	</serviceContact>

	<components>
		<system>
			<metadata>
				<sytemLongName>xxx Model</sytemLongName>
				<systemShortName>um</systemShortName>
				<systemIdentifier>urn:xxx:org:model1</systemIdentifier>
				<systemType> http://mmisw.org/mmi/20080520/obs.owl#numericalModel </systemType>
				<systemContacts>
					<systemContact type="http://mmisw.org/mmi/20080520/obs.owl#dataProvider" id="c1">
						<urlOrganization> org </urlOrganization>
						<longNameOrganization> a long name </longNameOrganization>
						<shortNameOrganization> shortName </shortNameOrganization>
						<individualName>FirtName lastName</individualName>
						<individualEmail>xxx@xxx.org</individualEmail>
					</systemContact>
				</systemContacts>
			</metadata>



			<output>

				<sourceConfiguration>
					<oostethys-netcdf
						xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
						<fileURL>
							http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_FVCOM_OCEAN_MASSBAY_FORECAST.nc.ascii?lon[28482],lat[28482],time[1:72],zeta[1:72][28482]
						</fileURL>
						<variables>
							<variable shortName="lat" dimension="latitude" uri="urn:ogc:phenomenon:latitude:wgs84"/>
							<variable shortName="lon" dimension="longitude" uri="urn:ogc:phenomenon:longitude:wgs84"/>
							<variable shortName="time" dimension="time" uri="urn:ogc:phenomenon:time:iso8601"/>
							<variable shortName="zeta" dimension="no" uri="urn:x:d"/>

						</variables>
					</oostethys-netcdf>


				</sourceConfiguration>

			</output>
		</system>
		
	</components>

</oostethys>

=== bermud/oostethys/component/server/java/oostethys-java-server/src/test/resources/oostethys_emptyString.xml
<?xml version="1.0" encoding="UTF-8"?>
<oostethys xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.oostethys.org/schemas/0.1.0/oostethys ../../main/resources/xml/oostethys/0.1.0/xsd/oostethys.xsd">


	<webServerURL>http://localhost:8080</webServerURL>
	<serviceContact type="http://mmisw.org/mmi/20080520/obs.owl#serviceProvider"
		id="a1">
		<urlOrganization>http://usgs.gov</urlOrganization>
		<longNameOrganization>
			USGS
		</longNameOrganization>
		<shortNameOrganization>usgs</shortNameOrganization>
		<individualName />
		<individualEmail />
	</serviceContact>

	<components>

		<system>
			<metadata>
				<sytemLongName> Model FVCOM - USGS - GOM</sytemLongName>
				<systemShortName>um2</systemShortName>
				<systemIdentifier>urn:usgs:gov:model:fvcom-gom</systemIdentifier>
				<systemType>http://mmisw.org/mmi/20080520/obs.owl#numericalModel</systemType>
				<systemContacts>
					<referencedContact ref="a1" />

				</systemContacts>
			</metadata>



			<output>

				<sourceConfiguration>

					<oostethys-netcdf
						xmlns="http://www.oostethys.org/schemas/0.1.0/oostethys-netcdf">
						<fileURL>umassb_scituate.nc</fileURL>

						<variables>
							<variable shortName="time" dimension="time"
								uri="urn:ogc:phenomenon:time:iso8601" />
							<variable shortName="lon" dimension="longitude"
								uri="urn:ogc:phenomenon:longitude:wgs84" />
							<variable shortName="lat" dimension="latitude"
								uri="urn:ogc:phenomenon:latitude:wgs84" />
							<variable shortName="elev" dimension="depth"
								uri="http://mmisw.org/ont/cf/parameter/depth" />




						</variables>
					</oostethys-netcdf>

				</sourceConfiguration>

			</output>
		</system>

	</components>

</oostethys>
